package dev.konraditurbe.storiesclient.control

import dev.konraditurbe.storiesclient.util.putLe16
import dev.konraditurbe.storiesclient.util.putLe32
import java.util.TreeMap

/**
 * The service set registered at the start of every control-channel session: the full 45-entry set the
 * official app registers (the SOC needs all of them to serve media). Every registration envelope is
 * generated BYTE-IDENTICAL to the captured frames; a `Flat.Builder`-built frame is a valid FlatBuffer but a
 * different byte layout, which the firmware rejects.
 *
 * Envelope: `[01][sub][idx][00][len:4 LE = total frame len][FlatBuffer]`. The glasses ALLOCATE a serviceClientId
 * per registration and return it in RegisterServiceClientResponse; `idx` is just our slot number.
 */
object ServiceRegistry {

    // Service names used for invokes / response routing (via the allocated-id map, never hardcoded ids).
    const val GET_CAPTURE_INFO = "stella:soc:get_capture_info"
    const val GET_ASSET = "stella:soc:get_asset_content_v2"
    const val GET_SYSTEM_INFO = "stella:soc:get_system_info"
    const val DEVICE_STATE = "stella:mcu:device_state"
    const val STATIONMODE = "stella:soc:stationmode_connect"
    const val START_WEBSERVER = "stella:soc:start_webserver"
    const val DELETE_CAPTURE = "stella:soc:delete_capture"
    const val MCU_SETTING = "stella:mcu:setting_request"

    /** A sub-0x04 (notify the phone provides) or sub-0x05 (request/response the phone invokes) service. */
    private class Service(val idx: Int, val sub: Int, val name: String, val requestType: String, val responseType: String)

    /** A sub-0x01 app registration (`code == null`) or sub-0x02/0x03 stream/topic registration. */
    private class Stream(val sub: Int, val idx: Int, val name: String, val code: String?)

    private fun svc(idx: Int, sub: Int, name: String, shortType: String) =
        Service(idx, sub, name, "stella.srvs.${shortType}Request", "stella.srvs.${shortType}Response")

    private val SERVICES = listOf(
        svc(0x02, 0x04, "stella:soc:notify_capture", "NotifyCapture"),
        svc(0x03, 0x04, "stella:soc:send_telemetry", "SendTelemetry"),
        svc(0x04, 0x04, "stella:soc:notify_crash_report", "CrashReportNotif"),
        svc(0x05, 0x04, "stella:assistant:phone:network_event", "AsstNetworkEvent"),
        svc(0x08, 0x05, "stella:state:stop_asst_stream", "StopAudioStream"),
        svc(0x09, 0x05, "stella:state:config_asst_stream", "ConfigAsstStream"),
        svc(0x0a, 0x05, "stella:audio:play_earcon", "PlayEarcon"),
        svc(0x0b, 0x05, "stella:wireless:bt_call_directive", "CallBluetooth"),
        svc(0x0c, 0x05, MCU_SETTING, "McuSetting"),
        svc(0x0d, 0x05, "stella:audio:control_raw_datacollection", "ControlRawDC"),
        svc(0x0e, 0x05, "stella:mcu:assistant_trigger_capture", "TriggerCapture"),
        svc(0x0f, 0x05, DEVICE_STATE, "DeviceStateQuery"),
        svc(0x10, 0x05, "stella:mcu:assistant_arbitrator", "AsstArbitrator"),
        svc(0x11, 0x05, "stella:wireless:btc_connection", "BtcConnection"),
        svc(0x12, 0x05, "stella:imu:control", "ControlImu"),
        svc(0x13, 0x05, "stella:mcu:mcu_flytrap_init", "McuFlytrapInit"),
        svc(0x19, 0x05, GET_CAPTURE_INFO, "GetCaptureInfo"),
        Service(0x1a, 0x05, GET_ASSET, "stella.srvs.GetAssetContentRequestV2", "stella.srvs.GetAssetContentResponseV2"),
        svc(0x1b, 0x05, GET_SYSTEM_INFO, "GetSystemInfo"),
        svc(0x1c, 0x05, START_WEBSERVER, "StartWebserver"),
        svc(0x1d, 0x05, "stella:soc:stop_webserver", "StopWebserver"),
        svc(0x1e, 0x05, "stella:soc:list_telemetry", "ListTelemetry"),
        svc(0x1f, 0x05, "stella:soc:delete_telemetry", "DeleteTelemetry"),
        svc(0x20, 0x05, STATIONMODE, "StaModeConnect"),
        svc(0x21, 0x05, "stella:soc:stationmode_disconnect", "StaModeDisconnect"),
        svc(0x22, 0x05, DELETE_CAPTURE, "DeleteCapture"),
        svc(0x23, 0x05, "stella:soc:generate_bug_report", "GenerateBugReport"),
        svc(0x24, 0x05, "stella:soc:add_bug_report_token", "AddBugReportToken"),
        svc(0x25, 0x05, "stella:soc:list_bug_report", "ListBugReport"),
        svc(0x26, 0x05, "stella:soc:delete_bug_report", "DeleteBugReport"),
        svc(0x27, 0x05, "stella:soc:delete_audio_capture", "DeleteAudioCapture"),
        svc(0x28, 0x05, "stella:soc:get_crashid_list", "ReportCrash"),
        svc(0x29, 0x05, "stella:soc:upload_success_request", "UploadSuccess"),
        svc(0x2a, 0x05, "stella:soc:get_wifi_capabilities", "GetWifiCapabilities"),
        svc(0x2b, 0x05, "stella:assistant:soc:network_event", "AsstNetworkEvent"),
        svc(0x2c, 0x05, "stella:soc:start_simile_migration", "SimileMigration"),
        svc(0x2d, 0x05, "stella:soc:home_ap_configure", "HomeApConfigure"),
    )

    /** `code` is the service's opaque 5-char `X.1Ox` identifier from the capture. */
    private val STREAMS = listOf(
        Stream(0x01, 0x01, "stella:app", null),
        Stream(0x02, 0x06, "stella:assistant:state", "X.1O7"),
        Stream(0x02, 0x07, "stella:assistant:phone:tts:data", "X.1O9"),
        Stream(0x03, 0x14, "stella:assistant:encoded:data", "X.1O3"),
        Stream(0x03, 0x15, "stella:audio:phone:tts:event", "X.1OC"),
        Stream(0x03, 0x16, "stella:mcu:device_state_update", "X.1O5"),
        Stream(0x03, 0x17, "stella:imu:data", "X.1Nz"),
        Stream(0x03, 0x18, "stella:wireless:bluetooth:hfp", "X.1OE"),
    )

    /** One registration to send, in index order. */
    class Registration(val idx: Int, val name: String, val frame: ByteArray)

    /** All registrations, sorted by registration index (the order the official app sends them). */
    fun registrations(): List<Registration> {
        val byIdx = TreeMap<Int, Registration>()
        for (s in SERVICES) byIdx[s.idx] = Registration(s.idx, s.name, serviceReg(s.idx, s.sub, s.name, s.requestType, s.responseType))
        for (s in STREAMS) byIdx[s.idx] = Registration(s.idx, s.name, if (s.code == null) appReg(s.idx, s.name) else streamReg(s.sub, s.idx, s.name, s.code))
        return byIdx.values.toList()
    }

    // ------------------------------------------------------------------------- byte-exact frame layouts

    private fun align4(n: Int) = (n + 3) and 3.inv()

    /** `[u32 len][ascii][0]`, 4-byte aligned by the caller's position arithmetic. */
    private fun ByteArray.putRegStr(pos: Int, s: ByteArray) {
        putLe32(pos, s.size); s.copyInto(this, pos + 4)
    }

    private fun ascii(s: String) = s.toByteArray(Charsets.US_ASCII)

    /** Wrap a registration FlatBuffer in the `[01][sub][idx][00][len:4 = TOTAL frame len]` envelope. */
    private fun envelope(sub: Int, idx: Int, fb: ByteArray): ByteArray {
        val env = ByteArray(8 + fb.size)
        env[0] = 0x01; env[1] = sub.toByte(); env[2] = idx.toByte(); env[3] = 0
        env.putLe32(4, env.size)
        fb.copyInto(env, 8)
        return env
    }

    /**
     * sub-0x04/0x05 RegisterServiceClientRequest: root(4) + vtable(12){f0@18,f1@12,f2@8,f3@4} +
     * table(20){soffset, f3=resp, f2=req, f1=svc, pad, f0=kind=3} + resp + req + svc strings.
     */
    internal fun serviceReg(idx: Int, sub: Int, svcName: String, reqType: String, respType: String): ByteArray {
        val rb = ascii(respType); val qb = ascii(reqType); val sb = ascii(svcName)
        val respPos = 36
        val reqPos = respPos + align4(rb.size + 5)
        val svcPos = reqPos + align4(qb.size + 5)
        val fb = ByteArray(svcPos + align4(sb.size + 5))
        fb.putLe32(0, 16)                                   // root offset
        fb.putLe16(4, 12); fb.putLe16(6, 20)                // vtable: vtableSize=12, tableSize=20
        fb.putLe16(8, 18); fb.putLe16(10, 12); fb.putLe16(12, 8); fb.putLe16(14, 4)   // f0@18, f1@12, f2@8, f3@4
        fb.putLe32(16, 12)                                  // table soffset (table 16 - vtable 4)
        fb.putLe32(20, respPos - 20)                        // f3 -> resp
        fb.putLe32(24, reqPos - 24)                         // f2 -> req
        fb.putLe32(28, svcPos - 28)                         // f1 -> svc
        fb.putLe16(34, 3)                                   // f0 = kind = 3 (offset 32 padding stays 0)
        fb.putRegStr(respPos, rb); fb.putRegStr(reqPos, qb); fb.putRegStr(svcPos, sb)
        return envelope(sub, idx, fb)
    }

    /** sub-0x01 app registration: single-string table `{f0: name}`. */
    internal fun appReg(idx: Int, name: String): ByteArray {
        val nb = ascii(name)
        val strPos = 20
        val fb = ByteArray(strPos + align4(nb.size + 5))
        fb.putLe32(0, 12)                                   // root offset
        fb.putLe16(6, 6); fb.putLe16(8, 8); fb.putLe16(10, 4)   // vtable: size=6, tableSize=8, f0@4
        fb.putLe32(12, 6)                                   // table soffset (table 12 - vtable 6)
        fb.putLe32(16, strPos - 16)                         // f0 -> name
        fb.putRegStr(strPos, nb)
        return envelope(0x01, idx, fb)
    }

    /** sub-0x02/0x03 stream/topic registration: `{f0:u16 kind=3 @tbl+14, f1:name @tbl+8, f2:code @tbl+4}`. */
    internal fun streamReg(sub: Int, idx: Int, name: String, code: String): ByteArray {
        val nb = ascii(name); val cb = ascii(code)
        val codePos = 32
        val namePos = codePos + align4(cb.size + 5)
        val fb = ByteArray(namePos + align4(nb.size + 5))
        fb.putLe32(0, 16)                                   // root offset
        fb.putLe16(6, 10); fb.putLe16(8, 16)                // vtable: vtableSize=10, tableSize=16
        fb.putLe16(10, 14); fb.putLe16(12, 8); fb.putLe16(14, 4)   // f0@14, f1@8, f2@4
        fb.putLe32(16, 10)                                  // table soffset (table 16 - vtable 6)
        fb.putLe32(20, codePos - 20)                        // f2 -> code
        fb.putLe32(24, namePos - 24)                        // f1 -> name
        fb.putLe16(30, 3)                                   // f0 = kind = 3 (offset 28 padding stays 0)
        fb.putRegStr(codePos, cb)
        fb.putRegStr(namePos, nb)
        return envelope(sub, idx, fb)
    }
}
